import React, { FormEvent, useState } from "react";
import { Link, Redirect, useHistory, useLocation } from "react-router-dom";
import { ProductGrid } from "../components/ShopUI";
import { products, money } from "../data/products";
import { useGlobals } from "../hooks/useGlobals";

export function HomeContent() { return <main><section className="trust-strip"><div><b>Direct from Korea</b><span>Curated Seoul quality</span></div><div><b>Secure checkout</b><span>Protected payments</span></div><div><b>Fast Uzbekistan delivery</b><span>Tracked to your door</span></div></section><section className="content-section"><div className="section-heading"><span className="eyebrow">CURATED FOR YOU</span><h2>The newest drop</h2><Link to="/products">View all →</Link></div><ProductGrid/></section><section className="brand-story"><span className="eyebrow">OUR BLUEPRINT</span><h2>Two cities.<br/>One street language.</h2><p>MNShop connects Seoul’s design culture with Tashkent’s independent spirit.</p></section></main>; }
export function CheckoutPage() { const g=useGlobals(); const history=useHistory(); const [step,setStep]=useState(1); const subtotal=g.basket.reduce((s,i)=>s+i.product.price*i.quantity,0); if(!g.authMember)return <Redirect to="/login?next=%2Fcheckout"/>; if(!g.basket.length)return <main className="page-shell"><div className="empty-state"><h2>Your cart is empty</h2><Link to="/products">Start shopping</Link></div></main>; return <main className="page-shell narrow"><span className="eyebrow">SECURE CHECKOUT</span><h1>Complete your order</h1><div className="steps">{["Summary","Delivery","Payment","Confirm"].map((s,i)=><span className={step>=i+1?"active":""} key={s}>{i+1}. {s}</span>)}</div><div className="checkout-card">{step===1&&<>{g.basket.map(i=><div className="summary-row" key={i.product.id}><span>{i.product.name} × {i.quantity}</span><b>{money(i.product.price*i.quantity)}</b></div>)}<div className="summary-row total"><span>Total</span><b>{money(subtotal)}</b></div></>}{step===2&&<div className="form-grid"><input placeholder="Full name" defaultValue={g.authMember.fullName}/><input placeholder="Phone number"/><input className="span-2" placeholder="Delivery address"/><input placeholder="City"/><input placeholder="ZIP code"/></div>}{step===3&&<div className="payment-methods"><button className="active">Stripe · Card</button><button>Payme</button><button>Click</button></div>}{step===4&&<div className="success-state"><h2>Ready to place your order?</h2><p>Server will verify current prices, stock, delivery and final total.</p></div>}<button className="primary-button" onClick={()=>step<4?setStep(step+1):(localStorage.setItem("mnshopOrders",JSON.stringify([{id:`MN-${Date.now().toString().slice(-6)}`,date:new Date().toISOString(),total:subtotal,status:"pending",items:g.basket},...JSON.parse(localStorage.getItem("mnshopOrders")||"[]")])),g.onDeleteAll(),g.setOrderBuilder(new Date()),history.push("/orders"))}>{step<4?"Continue":"Place order"}</button></div></main>; }
export function OrdersContent(){const g=useGlobals();if(!g.authMember)return <Redirect to="/login?next=%2Forders"/>;const orders=JSON.parse(localStorage.getItem("mnshopOrders")||"[]");return <main className="page-shell narrow"><span className="eyebrow">YOUR PURCHASES</span><h1>Orders</h1>{orders.length?orders.map((o:any)=><article className="order-card" key={o.id}><header><div><b>{o.id}</b><small>{new Date(o.date).toLocaleDateString()}</small></div><span className={`status status--${o.status}`}>{o.status}</span></header><div className="order-items">{o.items.map((i:any)=><span key={i.product.id}>{i.product.name} × {i.quantity}</span>)}</div><footer><span>Total</span><b>{money(o.total)}</b></footer></article>):<div className="empty-state"><h2>No orders yet</h2><p>Your order history will appear here.</p><Link to="/products">Explore products</Link></div>}</main>}
export function LikesPage(){const g=useGlobals();if(!g.authMember)return <Redirect to="/login?next=%2Flikes"/>;return <main className="page-shell"><div className="section-heading"><div><span className="eyebrow">SAVED FOR LATER</span><h1>Liked products</h1></div></div>{g.likedIds.length?<ProductGrid list={products.filter(p=>g.likedIds.includes(p.id))}/>:<div className="empty-state"><h2>No liked products</h2><Link to="/products">Find your style</Link></div>}</main>}
export function LoginPage(){const g=useGlobals();const history=useHistory();const location=useLocation();const next=new URLSearchParams(location.search).get("next")||"/";const submit=(e:FormEvent)=>{e.preventDefault();g.setAuthMember({id:"buyer-mn",fullName:"MNShop Buyer",email:"buyer@mnshop.uz",role:"BUYER"});history.push(next)};return <main className="auth-page"><form onSubmit={submit}><span className="eyebrow">WELCOME BACK</span><h1>Sign in to MNShop</h1><input required type="email" placeholder="Email"/><input required type="password" placeholder="Password"/><button className="primary-button">Sign in</button><p>New here? <Link to="/signup">Create account</Link></p></form></main>}
export function SignupPage(){return <main className="auth-page"><form><span className="eyebrow">JOIN THE MOVEMENT</span><h1>Create account</h1><input placeholder="Full name"/><input type="email" placeholder="Email"/><input type="password" placeholder="Password"/><button className="primary-button">Create account</button><p>Already a member? <Link to="/login">Sign in</Link></p></form></main>}
export function ProfilePage(){const g=useGlobals();if(!g.authMember)return <Redirect to="/login?next=%2Fmember-page"/>;return <main className="page-shell narrow"><span className="eyebrow">MY PAGE</span><h1>{g.authMember.fullName}</h1><div className="profile-card"><div className="profile-avatar">{g.authMember.fullName.slice(0,2)}</div><input defaultValue={g.authMember.fullName}/><input defaultValue={g.authMember.email}/><input placeholder="Phone"/><input placeholder="Address"/><button className="primary-button">Save profile</button><button className="danger-button" onClick={()=>g.setAuthMember(null)}>Log out</button></div></main>}
export function InfoPage({about=false}:{about?:boolean}){return <main className="page-shell narrow"><span className="eyebrow">{about?"OUR STORY":"MNShop SUPPORT"}</span><h1>{about?"Seoul design, Tashkent spirit.":"How can we help?"}</h1><div className="info-grid">{(about?["Korean quality","Uzbek community","Independent culture"]:["How does delivery work?","Can I exchange a size?","How can I track my order?"]).map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><h3>{x}</h3><p>Everything you need to know about MNShop products, ordering and customer care.</p></article>)}</div></main>}
